# fly.toml app configuration file generated for opera-icy-wildflower-4681 on 2024-07-26T11:18:25-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'opera-icy-wildflower-4681'
primary_region = 'dfw'
kill_signal = 'SIGTERM'

[build]

[deploy]
  release_command = '/app/bin/migrate'

[env]
  PHX_HOST = 'opera-icy-wildflower-4681.fly.dev'
  PORT = '8080'

[mounts]
  source = "database"
  destination = '/database'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
